# Generated by Django 5.1.2 on 2024-10-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Interprete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_integrantes', models.IntegerField(default=0)),
                ('descripcion_interprete', models.CharField(max_length=300)),
                ('oyentes_mensuales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('duracion', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('fecha', models.DateField()),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTop100Django.estilo')),
                ('intepretes', models.ManyToManyField(to='appTop100Django.interprete')),
            ],
        ),
    ]
