# Generated by Django 5.1.2 on 2024-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTop100Django', '0002_alter_cancion_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='interprete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='interpretes/'),
        ),
    ]
