# Generated by Django 5.1.1 on 2024-11-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTop100Django', '0003_interprete_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='canciones/'),
        ),
    ]
