# Generated by Django 5.1.2 on 2024-11-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTop100Django', '0005_alter_cancion_estilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancion',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTop100Django.estilo'),
        ),
    ]
