# Generated by Django 5.1.1 on 2024-12-02 09:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTop100Django', '0007_voto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='numero_votos',
        ),
        migrations.AddField(
            model_name='voto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='voto',
            name='valor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='voto',
            name='cancion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='appTop100Django.cancion'),
        ),
    ]
